// Unity Build Uber File generated by CMake
// This file is auto generated, do not manually edit it.

#include <StdAfx.h>
#include <C:/Users/panch/Documents/CRYENGINE Projects/Sidescroller/Code/Components/Player.cpp>
#include <C:/Users/panch/Documents/CRYENGINE Projects/Sidescroller/Code/Components/SpawnPoint.cpp>

